name: storybook

on: workflow_dispatch

jobs:
  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.14"
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - run: yarn workspace @linode/validation run build
      - uses: actions/upload-artifact@v3
        with:
          name: packages-validation-lib
          path: |
            packages/validation/lib

  build-sdk:
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.14"
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/download-artifact@v3
        with:
          name: packages-validation-lib
          path: packages/validation
      - run: yarn --frozen-lockfile
      - run: yarn workspace @linode/api-v4 run build
      - uses: actions/upload-artifact@v3
        with:
          name: packages-api-v4-lib
          path: |
            packages/api-v4/lib

  build:
    runs-on: ubuntu-latest
    needs: build-sdk
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.14"
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/download-artifact@v3
        with:
          name: packages-validation-lib
          path: packages/validation
      - uses: actions/download-artifact@v3
        with:
          name: packages-api-v4-lib
          path: packages/api-v4
      - run: yarn --frozen-lockfile
      - run: yarn workspace linode-manager run build-storybook
      - uses: actions/upload-artifact@v3
        with:
          name: storybook-build
          path: packages/manager/storybook-static

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: storybook-build
          path: storybook/build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_ENDPOINT: https://us-east-1.linodeobjects.com
          AWS_S3_BUCKET: ${{ secrets.STORYBOOK_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: storybook/build